version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - COINBASE_API_URL=https://api.coinbase.com/v3
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
