version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - COINBASE_API_URL=https://api.coinbase.com/v2
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
